const express = require('express')
//const { signup, signin, signout } = require('../controllers/auth')
const { userById, allUsers, getUser, updateUser, deleteUser } = require('../controllers/user')
//const { userSignupValidator } = require('../validator')
const { requireSignin } = require("../controllers/auth")
const router = express.Router()
//router.post("/signup", userSignupValidator, signup)
//router.post("/signin", signin)
router.get("/users", allUsers)
router.get("/users/:userId", requireSignin, getUser)
router.put("/users/:userId", requireSignin, updateUser)
router.delete("/users/:userId", requireSignin, deleteUser)
router.param("userId", userById)
module.exports = router;